src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Pseudo = null;

    #[ORM\Column(length: 255)]
    private ?string $ProfilePicture = null;

    #[ORM\Column(length: 255)]
    private ?string $ThemePref = null;

    #[ORM\Column]
    private ?int $Age = null;

    #[ORM\OneToMany(mappedBy: 'Author', targetEntity: Quizz::class, orphanRemoval: true)]
    private Collection $createdquizz;

    #[ORM\OneToMany(mappedBy: 'player', targetEntity: Play::class, orphanRemoval: true)]
    private Collection $playedquizz;

    #[ORM\OneToMany(mappedBy: 'player', targetEntity: Answer::class, orphanRemoval: true)]
    private Collection $answers;

    #[ORM\Column]
    private ?bool $Hide = null;

    public function __construct()
    {
        $this->createdquizz = new ArrayCollection();
        $this->playedquizz = new ArrayCollection();
        $this->answers = new ArrayCollection();
        
        $this
        ->setHide(false)
        ->setRoles(['ROLE_USER']);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        if ($this->getId() == 1){
            $this->setRoles(['ROLE_ADMIN']);
        }

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->ProfilePicture;
    }

    public function setProfilePicture(string $ProfilePicture): self
    {
        $this->ProfilePicture = $ProfilePicture;

        return $this;
    }

    public function getThemePref(): ?string
    {
        return $this->ThemePref;
    }

    public function setThemePref(string $ThemePref): self
    {
        $this->ThemePref = $ThemePref;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }

    /**
     * @return Collection<int, Quizz>
     */
    public function getCreatedquizz(): Collection
    {
        return $this->createdquizz;
    }

    public function addCreatedquizz(Quizz $createdquizz): self
    {
        if (!$this->createdquizz->contains($createdquizz)) {
            $this->createdquizz->add($createdquizz);
            $createdquizz->setAuthor($this);
        }

        return $this;
    }

    public function removeCreatedquizz(Quizz $createdquizz): self
    {
        if ($this->createdquizz->removeElement($createdquizz)) {
            // set the owning side to null (unless already changed)
            if ($createdquizz->getAuthor() === $this) {
                $createdquizz->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Play>
     */
    public function getPlayedquizz(): Collection
    {
        return $this->playedquizz;
    }

    public function addPlayedquizz(Play $playedquizz): self
    {
        if (!$this->playedquizz->contains($playedquizz)) {
            $this->playedquizz->add($playedquizz);
            $playedquizz->setPlayer($this);
        }

        return $this;
    }

    public function removePlayedquizz(Play $playedquizz): self
    {
        if ($this->playedquizz->removeElement($playedquizz)) {
            // set the owning side to null (unless already changed)
            if ($playedquizz->getPlayer() === $this) {
                $playedquizz->setPlayer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers->add($answer);
            $answer->setPlayer($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getPlayer() === $this) {
                $answer->setPlayer(null);
            }
        }

        return $this;
    }

    public function isHide(): ?bool
    {
        return $this->Hide;
    }

    public function setHide(bool $Hide): self
    {
        $this->Hide = $Hide;

        return $this;
    }

    public function __toString()
    {
        return $this->getPseudo();
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('roles')
            ->add('password')
            ->add('Pseudo')
            //->add('ProfilePicture')
            ->add('ThemePref')
            ->add('Age');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\QuizzRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('', name: 'app_user_profil', methods: ['GET'])]
    public function profil(QuizzRepository $quizzRepository): Response
    {
        return $this->render('user/profil.html.twig', [
            'quizzs' => $quizzRepository->findAllByUserId($this->getUser()->getId())
        ]);
    }

    // #[Route('/', name: 'app_user_index', methods: ['GET'])]
    // public function index(UserRepository $userRepository): Response
    // {
    //     return $this->render('user/index.html.twig', [
    //         'users' => $userRepository->findAll(),
    //     ]);
    // }

    // #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    // public function new(Request $request, UserRepository $userRepository): Response
    // {
    //     $user = new User();
    //     $form = $this->createForm(UserType::class, $user);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $userRepository->save($user, true);

    //         return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    //     }

    //     return $this->renderForm('user/new.html.twig', [
    //         'user' => $user,
    //         'form' => $form,
    //     ]);
    // }

    // #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    // public function show(User $user): Response
    // {
    //     return $this->render('user/show.html.twig', [
    //         'user' => $user,
    //     ]);
    // }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Identifiant</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Mot de passe</th>
                <th>Pseudo</th>
                <th>ThemePref</th>
                <th>Age</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.Pseudo }}</td>
                <td>{{ user.ThemePref }}</td>
                <td>{{ user.Age }}</td>
                <td>
                    <a href="{{ path('app_user_show', {'id': user.id}) }}">voir</a>
                    <a href="{{ path('app_user_edit', {'id': user.id}) }}">modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">aucun enregistrement</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_user_new') }}">Créer nouveau</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

templates/user/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ app.user.pseudo }}
{% endblock %}

{% block body %}
    <div class="container">
	<h3>{{app.user.pseudo}}</h3>

    <table class="table">
        <tbody>
            <tr>
                <th>Email</th>
                <td>{{ app.user.email }}</td>
            </tr>
            <tr>
                <th>ThemePref</th>
                <td>{{ app.user.ThemePref }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ app.user.Age }}</td>
            </tr>
        </tbody>
    </table>
    <a href="{{ path('app_user_edit', {'id': app.user.id}) }}">modifier</a>
    </div>

    <div class="container">
        <h3> Mes quizz : </h3>
        <table class="table">
  <thead>
    <tr>
      <th scope="col">Titre</th>
      <th scope="col">Theme</th>
      <th scope="col">Difficulté</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for quizz in quizzs %}
    <tr>
        <th>{{ quizz.title }}</th>
        <td> {{ quizz.Theme }} </td>
        <td> {{ quizz.Difficulty }} </td>
        <td> </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<a href="{{ path('app_quizz_new', {'id': app.user.id}) }}">Créer un quizz</a>
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur{% endblock %}

{% block body %}
    <h3>Utilisateur</h3>

    <table class="table">
        <tbody>
            <tr>
                <th>Identifiant</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ user.Pseudo }}</td>
            </tr>
            <tr>
                <th>ThemePref</th>
                <td>{{ user.ThemePref }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ user.Age }}</td>
            </tr>
        </tbody>
    </table>
    
    <a href="{{ path('app_user_index') }}">retour à la liste</a>

    <a href="{{ path('app_user_edit', {'id': user.id}) }}">modifier</a>


    {{ include('user/_delete_form.html.twig') }}
{% endblock %}