src/Entity/Questions.php
<?php

namespace App\Entity;

use App\Repository\QuestionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\This;

#[ORM\Entity(repositoryClass: QuestionsRepository::class)]
class Questions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Wording = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Answers = null;

    #[ORM\Column(length: 255)]
    private ?string $Image = null;

    #[ORM\Column(length: 255)]
    private ?string $CorrectAnswer = null;

    #[ORM\ManyToOne(targetEntity: Quizz::class,cascade : ["persist", "remove"], inversedBy: 'questions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Quizz $quizz = null;

    #[ORM\OneToMany(mappedBy: 'questions', targetEntity: Answer::class, orphanRemoval: true)]
    private Collection $playeranswers;

    public function __construct()
    {
        $this->playeranswers = new ArrayCollection();
    }
    private $questions;
    
    public function getquestions(){
        return $this->questions;
    }
    public function setQuestions($questions){
        $this->questions=$questions;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWording(): ?string
    {
        return $this->Wording;
    }

    public function setWording(string $Wording): self
    {
        $this->Wording = $Wording;

        return $this;
    }

    public function getAnswers(): ?string
    {
        return $this->Answers;
    }

    public function setAnswers(string $Answers): self
    {
        $this->Answers = $Answers;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getCorrectAnswer(): ?string
    {
        return $this->CorrectAnswer;
    }

    public function setCorrectAnswer(string $CorrectAnswer): self
    {
        $this->CorrectAnswer = $CorrectAnswer;

        return $this;
    }

    public function getQuizz(): ?Quizz
    {
        return $this->quizz;
    }

    public function setQuizz(?Quizz $quizz): self
    {
        $this->quizz = $quizz;

        return $this;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getPlayeranswers(): Collection
    {
        return $this->playeranswers;
    }

    public function addPlayeranswer(Answer $playeranswer): self
    {
        if (!$this->playeranswers->contains($playeranswer)) {
            $this->playeranswers->add($playeranswer);
            $playeranswer->setQuestions($this);
        }

        return $this;
    }
    public function __toString()
    {
        return $this->getWording();
    }
    public function removePlayeranswer(Answer $playeranswer): self
    {
        if ($this->playeranswers->removeElement($playeranswer)) {
            // set the owning side to null (unless already changed)
            if ($playeranswer->getQuestions() === $this) {
                $playeranswer->setQuestions(null);
            }
        }

        return $this;
    }
}

src/Entity/Quizz.php
<?php

namespace App\Entity;

use App\Repository\QuizzRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Entity;
use PhpParser\Node\Expr\Cast\Array_;
use Symfony\Component\Console\Question\Question;

#[ORM\Entity(repositoryClass: QuizzRepository::class)]
class Quizz
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Theme = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $Difficulty = null;

    #[ORM\ManyToOne(inversedBy: 'createdquizz')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $Author = null;
    
    #[ORM\OneToMany(mappedBy: 'quizz',cascade : ["persist", "remove"], targetEntity: Questions::class, orphanRemoval: true)]
    private Collection $questions;

    #[ORM\OneToMany(mappedBy: 'quizz', targetEntity: Play::class, orphanRemoval: true)]
    private Collection $played;

    #[ORM\Column]
    private ?bool $Hide = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->played = new ArrayCollection();
        $this->setHide(false);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTheme(): ?string
    {
        return $this->Theme;
    }

    public function setTheme(string $Theme): self
    {
        $this->Theme = $Theme;

        return $this;
    }

    public function getDifficulty(): ?int
    {
        return $this->Difficulty;
    }

    public function setDifficulty(int $Difficulty): self
    {
        $this->Difficulty = $Difficulty;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }  

    /**
     * @return Collection<int, Questions>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Questions $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions->add($question);
            $question->setQuizz($this);
        }

        return $this;
    }

    public function removeQuestion(Questions $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getQuizz() === $this) {
                $question->setQuizz(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Play>
     */
    public function getPlayed(): Collection
    {
        return $this->played;
    }

    public function addPlayed(Play $played): self
    {
        if (!$this->played->contains($played)) {
            $this->played->add($played);
            $played->setQuizz($this);
        }

        return $this;
    }

    public function removePlayed(Play $played): self
    {
        if ($this->played->removeElement($played)) {
            // set the owning side to null (unless already changed)
            if ($played->getQuizz() === $this) {
                $played->setQuizz(null);
            }
        }

        return $this;
    }

    public function isHide(): ?bool
    {
        return $this->Hide;
    }

    public function setHide(bool $Hide): self
    {
        $this->Hide = $Hide;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function __toString()
    {
        return $this->getTitle();
    }
}

src/Form/QuizzType.php
<?php

namespace App\Form;

use App\Entity\Quizz;
use App\Entity\Questions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class QuizzType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Title')
            ->add('Description', TextareaType::class)
            ->add('Theme', ChoiceType::class, [
                'choices'=> [
                    'Sport' => "Sport",
                    'Gaming' => "Gaming",
                    'Cinema' => "Cinema",
                    'Fun' => "Fun",
                    'Culutre Générale' => "Culutre Générale",
                    'Sciences' => "Sciences",
                    'Histoire' => "Histoire",
                    'Pop Culture' => "Pop Culture",
                    'Géographie' => "Géographie", 
                    'Animaux' => "Animaux",
                    'Autre' => "Autre"
                ]
            ])
            ->add('Difficulty', ChoiceType::class, [
                'choices' => [
                    '1' => 1,
                    '2' => 2,
                    '3' => 3,
                    '4' => 4,
                    '5' => 5
                ]
            ])
            ->add('Questions', CollectionType::class,[
                'entry_type' => QuestionsType::class,
                'label' => 'Questions',
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false
            ])
            ->add('valider', SubmitType::class)
    ;
        
 
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Quizz::class,
        ]);
    }
}

src/Controller/QuizzController.php
<?php

namespace App\Controller;

use App\Entity\Quizz;
use App\Form\QuizzType;
use App\Repository\QuizzRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/quizz')]
class QuizzController extends AbstractController
{
    #[Route('/', name: 'app_quizz_index', methods: ['GET'])]
    public function index(QuizzRepository $quizzRepository): Response
    {
        return $this->render('quizz/index.html.twig', [
            'quizzs' => $quizzRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_quizz_new', methods: ['GET', 'POST'])]
    public function new(Request $request, QuizzRepository $quizzRepository, EntityManagerInterface $entityManager): Response
    {
        $quizz = new Quizz();
        $quizz->setAuthor($this->getUser());
        $form = $this->createForm(QuizzType::class, $quizz);    
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($quizz);
            $entityManager->flush();
            $quizzRepository->save($quizz, true);
            return $this->redirectToRoute('app_quizz_show', ['id' => $quizz->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('quizz/new.html.twig', [
            'quizz' => $quizz,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_quizz_show', methods: ['GET'])]
    public function show(Quizz $quizz): Response
    {
        return $this->render('quizz/show.html.twig', [
            'quizz' => $quizz,
            'questions' => $quizz->getQuestions()
        ]);
    }

    #[Route('/{id}/edit', name: 'app_quizz_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Quizz $quizz, QuizzRepository $quizzRepository): Response
    {
        $form = $this->createForm(QuizzType::class, $quizz);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quizzRepository->save($quizz, true);

            return $this->redirectToRoute('app_quizz_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('quizz/edit.html.twig', [
            'quizz' => $quizz,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_quizz_delete', methods: ['POST'])]
    public function delete(Request $request, Quizz $quizz, QuizzRepository $quizzRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$quizz->getId(), $request->request->get('_token'))) {
            $quizzRepository->remove($quizz, true);
        }

        return $this->redirectToRoute('app_quizz_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/quizz/_delete_form.html.twig
<form method="post" action="{{ path('app_quizz_delete', {'id': quizz.id}) }}" onsubmit="return confirm(Etes vous sûr de supprimer cet objet?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quizz.id) }}">
    <button class="btn btn-danger">Supprimer le quizz</button>
</form>

templates/quizz/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/quizz/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Quizz{% endblock %}

{% block body %}
    <h1>Edit Quizz</h1>

    {{ include('quizz/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_quizz_index') }}">back to list</a>

    {{ include('quizz/_delete_form.html.twig') }}
{% endblock %}

templates/quizz/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quizz index{% endblock %}

{% block body %}
    <h1>Quizz index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Theme</th>
                <th>Difficulty</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for quizz in quizzs %}
            <tr>
                <td>{{ quizz.id }}</td>
                <td>{{ quizz.Theme }}</td>
                <td>{{ quizz.Difficulty }}</td>
                <td>
                    <a href="{{ path('app_quizz_show', {'id': quizz.id}) }}">show</a>
                    <a href="{{ path('app_quizz_edit', {'id': quizz.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_quizz_new') }}">Create new</a>
{% endblock %}

templates/quizz/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Ajout Quizz
{% endblock %}

{% block body %}
    <div class="container">
    <h1>Ajouter un Quizz</h1>
    {{ form_start(form) }}
        {{ form_row(form.Title) }}
        {{ form_row(form.Description) }}
        {{ form_row(form.Theme) }}
        {{ form_row(form.Difficulty) }}
        <div class="container" id="questions" data-prototype="{{ form_row(form.Questions.vars.prototype)|e('html_attr') }}">
            {{ form_row(form.Questions) }}
            <span></span>
        </div>
    {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        let collection, boutonAjout, span;
        window.onload = () => {
            collection = document.querySelector("#questions");
            span = collection.querySelector("span");
            boutonAjout = document.createElement("button");
            boutonAjout.className = "btn btn-primary";
            boutonAjout.innerText = "Ajouter une questions";
            let nouveauBouton = span.append(boutonAjout);
            collection.dataset.index = collection.querySelectorAll("input").length;
            boutonAjout.addEventListener("click", function(){
                addButton(collection, nouveauBouton);
            });
        }
        function addButton(collection, nouveauBouton){
            let prototype = collection.dataset.prototype;
            let index = collection.dataset.index;
            prototype = prototype.replace(/__name__/g, index);
            let content = document.createElement("html");
            content.innerHTML = prototype;
            let newForm = content.querySelector("div");
            let boutonSuppr = document.createElement("button");
            boutonSuppr.type = "button";
            boutonSuppr.className = "btn btn-danger";
            boutonSuppr.id = "delete-departement-" + index;
            boutonSuppr.innerText = "Supprimer cette questions";
            newForm.append(boutonSuppr);
            collection.dataset.index++;
            let boutonAjout = collection.querySelector(".ajout-questions");
            span.insertBefore(newForm, boutonAjout);
            boutonSuppr.addEventListener("click", function(){
                this.previousElementSibling.parentElement.remove();
            })
        }
    </script>
{% endblock %}

templates/quizz/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quizz{% endblock %}

{% block body %}
    <div class="container">
    <h3> {{ quizz.Title }} </h3>
    <p> {{quizz.Description}} </p>
    <table class="table">
        <tbody>
            <tr>
                <th>Theme</th>
                <td>{{ quizz.Theme }}</td>
            </tr>
            <tr>
                <th>Difficulté</th>
                <td>{{ quizz.Difficulty }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_quizz_edit', {'id': quizz.id}) }}">modifier</a>
    </div>

    <div class="container">
        <h3> Questions : </h3>
        <table class="table">
  <thead>
    <tr>
      <th scope="col">Question</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for question in questions %}
    <tr>
        <th>{{question.wording}}</th>
        <td>Mark</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

    <a href="{{ path('app_questions_new', {'quizz': quizz}) }}">ajouter une question</a>
    </div>

    {{ include('quizz/_delete_form.html.twig') }}
{% endblock %}